### ISSUE TITLE
Feature-Request: Copyright header over each generated file

### ISSUE THREAD

**Issue by stbischof** [congo-cc/congo-parser-generator#1]
Additional to the header:
```
/* Generated by: CongoCC Parser Generator. Do not edit.
```
I would like to add a Copyright header. (even if its just generated code).

**Comment by revusky** [comment]
Okay, it is there now. Easy enough and since this is the first feature request
on CongoCC, it is good to hit the ground running.

So you can add the setting `COPYRIGHT_BLURB`, something like:

     COPYRIGHT_BLURB="\n * IT IS MINE, ALL MINE!\n";

at the top of a grammar.

**Comment by stbischof** [comment]
Thank you @revusky . Thats great.

looking forward to first releases. (even if its still from the `/bin` Folder;-)

**Comment by revusky** [comment]
> Thank you @revusky . Thats great.
> 
> looking forward to first releases. (even if its still from the `/bin` Folder;-)

Well, it's usable actually. Just, as before, grab the latest build [here](https://congocc.org/download/congocc-full.jar). (The one checked into the `/bin` folder is actually the bootstrap jar, which was the jarfile used to build, so it is typically a bit older. CongoCC already is self-bootstrapping.)

The issues you're likely to run into now are that things are a bit unstable in terms of the package layout and things like that changing. And, as I said elsewhere, it doesn't support any of the legacy syntax. But really, the tool is quite solid. I mean, it runs all the same tests as before, so it can build a java parser, a python parser, a Csharp parser, and it can rebuild itself, so...

Out of curiosity, how long have you been using this? (I mean JavaCC 21, I guess)

**Comment by stbischof** [comment]
I switches to new layout. I am at the start of a new iteration of the project so it might be no problem to switch. think the future is here.

**Comment by stbischof** [comment]
@revusky i Think we can close this. works like a charm.

**Comment by revusky** [comment]
> I switches to new layout. I am at the start of a new iteration of the project so it might be no problem to switch. think the future is here.

I think that's definitely the right decision. For one thing, Congo is just going to be better, since JavaCC 21 still made various concessions to backward compatibility, so, for new projects, it's definitely the way to go. And you'll get a better level of support. Generally, I've decided on a policy of no backporting, so any new features are only going into CongoCC. 

I just wrote this today and you may find it useful: https://discuss.congocc.org/d/30-migrating-to-congocc-any-snags-should-be-quite-minor

By all means, consider signing up on that forum. Not to worry, it's very low-volume. 

> 
> I didn't fount this link elsewhere https://congocc.org/download/congocc-full.jar

Oh, that's true. I suppose it's not mentioned anywhere! I must have been counting on people to read my mind!
