### ISSUE TITLE
Quick start guide link 404

### ISSUE THREAD

**Issue by mingodad** [congo-cc/congo-parser-generator#8]
On the readme this link https://github.com/congo-cc/congo-parser-generator/blob/main is actually a 404 github page.

**Comment by revusky** [comment]
Hi, yes, that is broken! I was actually aware of that. I wrote the README (finally) there just a couple of days ago, and consciously put that there without a proper link, intending to address the problem in the next week at most.

But I appreciate your telling me, mostly because it's nice to know that somebody actually is looking for the information. It does light a fire under my feet to get moving on that!

I'll answer your other issue separately. 

Por cierto, ¿eres español?

**Comment by mingodad** [comment]
Yes ! I am from Málaga .

**Comment by vsajip** [comment]
I'll close this, as the link now appears to be working as expected.
